"""Candle provenance — every row can say where it came from and what is derived.

Order matters here and is the whole reason this is hand-written rather than
autogenerated: columns are added nullable, backfilled from data already in
the table, and only then tightened. Adding `source NOT NULL` in one step
against a populated table fails, and adding it with a made-up default is
worse — it would relabel unknown rows as trustworthy.

Revision ID: 0002
Revises: 0001
"""
from collections.abc import Sequence
from datetime import UTC, timedelta, timezone

import sqlalchemy as sa
from alembic import op
from app.data.migration_guards import add_column_if_absent, create_index_if_absent

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

IST = timezone(timedelta(hours=5, minutes=30))
BACKFILL_CHUNK = 1000


def _backfill_session_date() -> None:
    """Derive the IST trading date for every existing row.

    Done in Python rather than SQL because the timezone cast has no portable
    spelling — Postgres wants `AT TIME ZONE`, SQLite has no timezone support
    at all — and getting it wrong would split sessions across two dates,
    which the gap diagnostics would then report as missing data forever.
    """
    conn = op.get_bind()

    # A typed table stub rather than raw text: SQLite stores datetimes as
    # strings and only applies a result processor when the column's type is
    # known, so `SELECT timestamp` through `sa.text` hands back `str` and the
    # conversion below silently breaks.
    candles = sa.table(
        "candles",
        sa.column("id", sa.Integer),
        sa.column("timestamp", sa.DateTime(timezone=True)),
        sa.column("session_date", sa.Date),
    )
    rows = conn.execute(
        sa.select(candles.c.id, candles.c.timestamp)
        .where(candles.c.session_date.is_(None))
    ).fetchall()

    updates = []
    for row_id, ts in rows:
        if ts is None:
            continue
        # SQLite hands back naive datetimes; everything written here is UTC.
        moment = ts if ts.tzinfo else ts.replace(tzinfo=UTC)
        updates.append({"row_id": row_id, "sd": moment.astimezone(IST).date()})

    stmt = sa.text("UPDATE candles SET session_date = :sd WHERE id = :row_id")
    for start in range(0, len(updates), BACKFILL_CHUNK):
        conn.execute(stmt, updates[start : start + BACKFILL_CHUNK])


def upgrade() -> None:
    add = add_column_if_absent
    add("candles", sa.Column("session_date", sa.Date(), nullable=True))
    add("candles", sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True))
    add("candles", sa.Column("volume_is_synthetic", sa.Boolean(), nullable=False,
                             server_default=sa.text("FALSE")))
    add("candles", sa.Column("revision", sa.Integer(), nullable=False,
                             server_default=sa.text("0")))

    _backfill_session_date()

    # A session whose bars all carry the same volume is a session where the
    # volume is a placeholder, not a measurement. Yahoo publishes no volume
    # for ^NSEI and the free broker substitutes a constant, so these rows
    # are already in the archive looking exactly like real ones.
    op.execute(sa.text("""
        UPDATE candles SET volume_is_synthetic = TRUE
        WHERE session_date IS NOT NULL
          AND EXISTS (
            SELECT 1 FROM candles c2
             WHERE c2.symbol = candles.symbol
               AND c2.timeframe = candles.timeframe
               AND c2.session_date = candles.session_date
             GROUP BY c2.symbol, c2.timeframe, c2.session_date
            HAVING COUNT(DISTINCT c2.volume) = 1
          )
    """))

    # Rows that predate the required-source rule are labelled honestly
    # rather than assumed to be good.
    op.execute(sa.text("UPDATE candles SET source = 'unknown' WHERE source IS NULL"))

    with op.batch_alter_table("candles") as batch:
        batch.alter_column("source", existing_type=sa.String(16), nullable=False)

    create_index_if_absent("ix_candles_session_date", "candles", ["session_date"])
    create_index_if_absent("ix_candle_session", "candles",
                           ["symbol", "timeframe", "session_date"])


def downgrade() -> None:
    from app.data.migration_guards import drop_index_if_present
    drop_index_if_present("ix_candle_session", "candles")
    drop_index_if_present("ix_candles_session_date", "candles")
    with op.batch_alter_table("candles") as batch:
        batch.alter_column("source", existing_type=sa.String(16), nullable=True)
    op.drop_column("candles", "revision")
    op.drop_column("candles", "volume_is_synthetic")
    op.drop_column("candles", "ingested_at")
    op.drop_column("candles", "session_date")
